# Generated by Django 3.2.25 on 2026-04-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_builder_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
